# Generated by Django 5.1.7 on 2025-12-27 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('quarter_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quarter_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('section_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDocument',
            fields=[
                ('analysis_document_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('analysis_doc_title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('test_start_date', models.DateField(null=True)),
                ('analysis_doc', models.FileField(null=True, upload_to='analysis_documents/')),
                ('status', models.BooleanField(default=False)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.teacher')),
                ('quarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.quarter')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.section')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDocumentInsights',
            fields=[
                ('analysis_document_insights_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('insights', models.JSONField(null=True)),
                ('ai_insights', models.JSONField(null=True)),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDocumentStatistic',
            fields=[
                ('analysis_document_statistic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('median', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('mode', models.FloatField()),
                ('total_students', models.IntegerField()),
                ('mean_passing_threshold', models.FloatField()),
                ('heatmap', models.FileField(null=True, upload_to='heatmaps/')),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('idempotency_key', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('returned_draft_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedScore',
            fields=[
                ('predicted_score_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('formative_assessment_number', models.CharField(max_length=5)),
                ('predicted_status', models.CharField(max_length=20, null=True)),
                ('passing_threshold', models.FloatField()),
                ('max_score', models.FloatField(null=True)),
                ('analysis_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.student')),
            ],
        ),
        migrations.CreateModel(
            name='FormativeAssessmentScore',
            fields=[
                ('formative_assessment_score_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('formative_assessment_number', models.CharField(max_length=5)),
                ('passing_threshold', models.FloatField()),
                ('analysis_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScoresStatistic',
            fields=[
                ('student_scores_statistic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('median', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('mode', models.FloatField(null=True)),
                ('passing_rate', models.FloatField()),
                ('failing_rate', models.FloatField()),
                ('lineplot', models.FileField(null=True, upload_to='lineplots/')),
                ('heatmap', models.FileField(null=True, upload_to='heatmaps/')),
                ('performance_comparison_chart', models.FileField(null=True, upload_to='performance_comparisons/')),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.student')),
            ],
        ),
        migrations.CreateModel(
            name='TestDraft',
            fields=[
                ('test_draft_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('test_content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('topic_name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FormativeAssessmentStatistic',
            fields=[
                ('formative_assessment_statistic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('formative_assessment_number', models.CharField(max_length=5)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('median', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('mode', models.FloatField(null=True)),
                ('passing_rate', models.FloatField()),
                ('failing_rate', models.FloatField()),
                ('passing_threshold', models.FloatField()),
                ('max_score', models.FloatField(null=True)),
                ('histogram', models.FileField(null=True, upload_to='histograms/')),
                ('scatterplot', models.FileField(null=True, upload_to='scatterplots/')),
                ('bar_chart', models.FileField(null=True, upload_to='bar_charts/')),
                ('boxplot', models.FileField(null=True, upload_to='boxplots/')),
                ('student_comparison_chart', models.FileField(null=True, upload_to='student_comparison_charts/')),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
                ('fa_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.testtopic')),
            ],
        ),
        migrations.CreateModel(
            name='TestTopicMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('test_number', models.CharField(max_length=5)),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_topics', to='Test_Management.analysisdocument')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.testtopic')),
            ],
            options={
                'unique_together': {('analysis_document', 'test_number')},
            },
        ),
    ]
