# Generated by Django 5.1.7 on 2025-12-27 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdraft',
            old_name='user',
            new_name='user_teacher',
        ),
        migrations.AddField(
            model_name='testdraft',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.quarter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdraft',
            name='section_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdraft',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdraft',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
