# Generated by Django 5.2 on 2025-12-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0002_rename_user_testdraft_user_teacher_testdraft_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formativeassessmentscore',
            name='topic_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Test_Management.testtopicmapping'),
        ),
        migrations.AddField(
            model_name='testtopicmapping',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formativeassessmentscore',
            name='passing_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictedscore',
            name='predicted_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testtopic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.subject'),
        ),
    ]
