# Generated by Django 5.2 on 2025-12-28 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_initial'),
        ('Test_Management', '0003_formativeassessmentscore_topic_mapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedscore',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.student'),
        ),
        migrations.AlterField(
            model_name='formativeassessmentscore',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.student'),
        ),
        migrations.AlterField(
            model_name='studentscoresstatistic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.student'),
        ),
        migrations.RenameField(
            model_name='analysisdocument',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='analysisdocument',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='analysisdocument',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
