# Generated by Django 5.2 on 2025-12-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0004_alter_predictedscore_student_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testtopicmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testtopic',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testtopic',
            name='test_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.RemoveField(
            model_name='testtopicmapping',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='testtopicmapping',
            name='test_number',
        ),
    ]
