# Generated by Django 5.2 on 2025-12-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0005_alter_testtopicmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formativeassessmentscore',
            old_name='formative_assessment_number',
            new_name='test_number',
        ),
        migrations.RenameField(
            model_name='predictedscore',
            old_name='formative_assessment_number',
            new_name='test_number',
        ),
    ]
