# Generated by Django 5.2 on 2025-12-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0006_rename_formative_assessment_number_formativeassessmentscore_test_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdocument',
            name='post_test_max_score',
            field=models.FloatField(null=True),
        ),
    ]
