# Generated by Django 5.1.7 on 2025-03-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0007_alter_analysisdocument_analysis_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section_id',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
