# Generated by Django 5.2 on 2026-01-02 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_student_first_name_alter_student_last_name_and_more'),
        ('Test_Management', '0008_teacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualPostTest',
            fields=[
                ('actual_post_test_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_post_tests', to='Test_Management.analysisdocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.student')),
            ],
        ),
    ]
