# Generated by Django 5.2 on 2026-01-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_student_first_name_alter_student_last_name_and_more'),
        ('Test_Management', '0009_actualposttest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actualposttest',
            unique_together={('analysis_document', 'student')},
        ),
    ]
