# Generated by Django 5.1.7 on 2025-03-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0009_remove_predictedscore_formative_assessment_score_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictedscore',
            old_name='analysis_doc',
            new_name='analysis_document',
        ),
    ]
