# Generated by Django 5.2 on 2026-01-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0010_alter_actualposttest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscoresstatistic',
            name='max_possible_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentscoresstatistic',
            name='sum_scores',
            field=models.FloatField(null=True),
        ),
    ]
