# Generated by Django 5.1.7 on 2025-03-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0010_rename_analysis_doc_predictedscore_analysis_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdocument',
            name='test_start_date',
            field=models.DateField(null=True),
        ),
    ]
