# Generated by Django 5.2 on 2026-01-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0011_studentscoresstatistic_max_possible_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualposttest',
            options={'ordering': ['-actual_post_test_id']},
        ),
        migrations.AlterModelOptions(
            name='analysisdocument',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='analysisdocumentinsights',
            options={'ordering': ['-analysis_document_insights_id']},
        ),
        migrations.AlterModelOptions(
            name='analysisdocumentstatistic',
            options={'ordering': ['-analysis_document_statistic_id']},
        ),
        migrations.AlterModelOptions(
            name='formativeassessmentscore',
            options={'ordering': ['-date', '-formative_assessment_score_id']},
        ),
        migrations.AlterModelOptions(
            name='formativeassessmentstatistic',
            options={'ordering': ['-formative_assessment_statistic_id']},
        ),
        migrations.AlterModelOptions(
            name='idempotencykey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='predictedscore',
            options={'ordering': ['-date', '-predicted_score_id']},
        ),
        migrations.AlterModelOptions(
            name='quarter',
            options={'ordering': ['-quarter_id']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-section_id']},
        ),
        migrations.AlterModelOptions(
            name='studentscoresstatistic',
            options={'ordering': ['-student_scores_statistic_id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-subject_id']},
        ),
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testdraft',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testtopic',
            options={'ordering': ['-topic_id']},
        ),
        migrations.AlterModelOptions(
            name='testtopicmapping',
            options={'ordering': ['-mapping_id']},
        ),
    ]
