# Generated by Django 5.1.7 on 2025-04-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0015_remove_analysisdocumentstatistic_failing_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formativeassessmentstatistic',
            name='fa_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.testtopic'),
        ),
        migrations.CreateModel(
            name='StudentScoresStatistic',
            fields=[
                ('student_scores_statistic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('median', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('mode', models.FloatField()),
                ('passing_rate', models.FloatField()),
                ('failing_rate', models.FloatField()),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.student')),
            ],
        ),
    ]
