# Generated by Django 5.1.7 on 2025-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0021_formativeassessmentstatistic_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='formativeassessmentstatistic',
            name='boxplot',
            field=models.FileField(null=True, upload_to='boxplots/'),
        ),
        migrations.AddField(
            model_name='formativeassessmentstatistic',
            name='histogram',
            field=models.FileField(null=True, upload_to='histograms/'),
        ),
        migrations.AddField(
            model_name='formativeassessmentstatistic',
            name='scatterplot',
            field=models.FileField(null=True, upload_to='scatterplots/'),
        ),
    ]
