# Generated by Django 5.1.7 on 2025-04-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0025_analysisdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscoresstatistic',
            name='radar_chart',
            field=models.FileField(null=True, upload_to='radar_charts/'),
        ),
    ]
