# Generated by Django 5.1.7 on 2025-04-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0026_studentscoresstatistic_radar_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscoresstatistic',
            name='radar_chart',
        ),
    ]
