# Generated by Django 5.1.7 on 2025-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0027_remove_studentscoresstatistic_radar_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedscore',
            name='max_score',
            field=models.FloatField(null=True),
        ),
    ]
