# Generated by Django 5.1.7 on 2025-04-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0029_formativeassessmentstatistic_student_comparison_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscoresstatistic',
            name='performance_comparison_chart',
            field=models.FileField(null=True, upload_to='performance_comparisons/'),
        ),
    ]
