# Generated by Django 5.1.7 on 2025-04-25 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0030_studentscoresstatistic_performance_comparison_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDocumentInsights',
            fields=[
                ('analysis_document_insights_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('insights', models.JSONField(null=True)),
                ('ai_insights', models.JSONField(null=True)),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
            ],
        ),
    ]
