# Generated by Django 5.1.7 on 2025-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0012_testtopic_testtopicmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtopic',
            name='topic_name',
            field=models.CharField(max_length=100),
        ),
    ]
