# Generated by Django 5.1.7 on 2025-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0016_formativeassessmentstatistic_fa_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedscore',
            name='predicted_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
