# Generated by Django 5.1.7 on 2025-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0018_analysisdocumentstatistic_mean_passing_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedscore',
            name='passing_threshold',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
