# Generated by Django 5.1.7 on 2025-04-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0023_formativeassessmentstatistic_bar_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscoresstatistic',
            name='heatmap',
            field=models.FileField(null=True, upload_to='heatmaps/'),
        ),
        migrations.AddField(
            model_name='studentscoresstatistic',
            name='lineplot',
            field=models.FileField(null=True, upload_to='lineplots/'),
        ),
    ]
