# Generated by Django 5.1.7 on 2025-04-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0024_studentscoresstatistic_heatmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdocument',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
