# Generated by Django 5.1.7 on 2025-04-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0028_predictedscore_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='formativeassessmentstatistic',
            name='student_comparison_chart',
            field=models.FileField(null=True, upload_to='student_comparison_charts/'),
        ),
    ]
