# Generated by Django 5.1.7 on 2025-03-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedscore',
            name='formative_assessment_score_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.formativeassessmentscore'),
            preserve_default=False,
        ),
    ]
