# Generated by Django 5.1.7 on 2025-03-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0003_remove_teacher_first_name_remove_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('quarter_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quarter_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='analysisdocument',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.quarter'),
        ),
        migrations.AddField(
            model_name='analysisdocument',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.subject'),
        ),
    ]
