# Generated by Django 5.1.7 on 2025-03-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('Test_Management', '0004_quarter_subject_analysisdocument_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdocument',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.teacher'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
