# Generated by Django 5.1.7 on 2025-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0005_alter_analysisdocument_teacher_id_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdocument',
            name='analysis_doc',
            field=models.FileField(upload_to='media/analysis_documents/'),
        ),
    ]
