# Generated by Django 5.1.7 on 2025-03-29 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0008_remove_student_section_id_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedscore',
            name='formative_assessment_score_id',
        ),
        migrations.AddField(
            model_name='formativeassessmentscore',
            name='analysis_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument'),
        ),
        migrations.AddField(
            model_name='predictedscore',
            name='analysis_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument'),
        ),
    ]
