# Generated by Django 5.1.7 on 2025-04-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Management', '0014_analysisdocumentstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisdocumentstatistic',
            name='failing_rate',
        ),
        migrations.RemoveField(
            model_name='analysisdocumentstatistic',
            name='passing_rate',
        ),
        migrations.CreateModel(
            name='FormativeAssessmentStatistic',
            fields=[
                ('formative_assessment_statistic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('formative_assessment_number', models.CharField(max_length=5)),
                ('mean', models.FloatField()),
                ('standard_deviation', models.FloatField()),
                ('median', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('mode', models.FloatField()),
                ('passing_rate', models.FloatField()),
                ('failing_rate', models.FloatField()),
                ('analysis_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_Management.analysisdocument')),
            ],
        ),
    ]
