# Generated by Django 5.2 on 2026-01-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_student_first_name_alter_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['-id']},
        ),
    ]
