# Generated by Django 5.2 on 2026-03-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
