# Generated by Django 5.2 on 2026-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_student_initial_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
